import pysam
import sys

## Usage: MergeBC2Bam.py BC.dic(Barcode dictionary file generated by MakeBC.ATAC.I2.py) Bam output prefix

##Make Barcode dictionary
BCfilename=sys.argv[1]
Bamfilename=sys.argv[2]
OutPre=sys.argv[2]

BCcelldic={}
# i=0
with open(BCfilename) as f:
    while True:
        # print(i)
        # i=i+1
        Line=f.readline().strip()
        if Line=="":
            break
        else:
            LineArray=Line.split()
            BCcelldic[LineArray[0][1:]]=LineArray[1]

##Read in the bam by pysam and add Cell barcode and UMI
TPLT= pysam.AlignmentFile(Bamfilename, "rb")
outSam= pysam.AlignmentFile(OutPre[:-4]+".tagged.bam", "wb", template=TPLT)

Bam=pysam.AlignmentFile(Bamfilename,"rb")
for read in Bam.fetch(until_eof=True):
    Qname=read.query_name
    if Qname in BCcelldic.keys():
        read.set_tag('BC',BCcelldic[Qname])
        outSam.write(read)
    # print(str(x))
