""" 
Preprocess.py
This script split the mtDNA bam files for in-paralell variant calling

Syntax: python Preprocess.py -i -c -b -o -g -bt -sd
Options: --input or -i: uniqmapped.bam files generated by MultiomeATAC_mito.sh, REQUIRED.
         --ncores or -c: Number of cores to run the main job in parallel. REQUIRED.
         --barcodes or -b: The csv file indicating the qualified cell names. barcodes.tsv generated by RNAbc2ATAC.R, required
         --output or -o: The name of folder to be created that will contain the analyzed results, default=Out_mitoConsensus
         --mito-genome or -g: mitochondrial genome configuration. Choose hg19, hg38, mm10, (etc.) or a custom .fasta file,  Default = rCRS
         --barcode-tag or -bt: tag name in bam file, 10X is BC. Default = BC
         --script-dir or -sd: default = "/lab/solexa_weissman/cweng/Packages/REDEEM-V/mitoConsensus/ The path to REDEEM-V/mitoConsensus/

Acknowledgment: Inherited some of the codes from https://github.com/caleblareau/mgatk by Caleb Lareau et al. 
"""

import argparse
from multiprocessing import Pool
from mgatkHelp import *
from itertools import repeat
import pysam
import os
import sys
import subprocess
import time


import click



def process_bam(input_bam, output_bam):
    with pysam.AlignmentFile(input_bam, "rb") as infile, pysam.AlignmentFile(output_bam, "wb", template=infile) as outfile:
        for read in infile:
            if not read.is_unmapped:
                outfile.write(read)
def process_bam_single_pass(input_bam, barcode_files, output_dir, barcode_tag, mito_chr, prefix=""):
    # Step 1: Read all barcode files into a dictionary mapping barcode -> output file
    barcode_to_file = {}
    file_handlers = {}
    
    for bf in barcode_files:
        basename = os.path.basename(os.path.splitext(bf)[0])
        output_bam = os.path.join(output_dir, f"{prefix}{basename}.bam")
        print(f"Output bam name: {output_bam}")
        
        # Read barcodes from this file
        with open(bf, 'r') as f:
            barcodes = [line.strip() for line in f if line.strip()]
            
        # Map each barcode to its output file
        for bc in barcodes:
            barcode_to_file[bc] = output_bam
    
    # Step 2: Process BAM file in a single pass
    print(f"Processing BAM file: {input_bam}")
    
    with pysam.AlignmentFile(input_bam, "rb") as infile:
        # Step 3: Process reads and write to appropriate files
        contig = mito_chr.split()[0]

        for read in infile.fetch(contig, multiple_iterators=True):
            try:
                bc = read.get_tag(barcode_tag)
                if bc in barcode_to_file:
                    output_file = barcode_to_file[bc]
                    
                    # Create output file handler if not already created
                    if output_file not in file_handlers:
                        file_handlers[output_file] = pysam.AlignmentFile(output_file, "wb", template=infile)
                    
                    # Write the read
                    file_handlers[output_file].write(read)
            except KeyError:
                continue  # Skip reads without barcode tag
    
    # Step 4: Close all file handlers
    for handler in file_handlers.values():
        handler.close()
    
    # Step 5: Sort and index each output file
    for output_file in set(file_handlers.keys()):
        print(f"Sorting and indexing: {output_file}")
        try:
            # Create a temporary sorted BAM
            sorted_bam = output_file + ".sorted.bam"
            pysam.sort("-o", sorted_bam, output_file)
            # Replace the original with the sorted one
            os.replace(sorted_bam, output_file)
            # Index
            pysam.index(output_file)
        except Exception as e:
            print(f"Error processing {output_file}: {e}")
@click.command()
@click.version_option()
@click.option('--input', '-i', default=".", required=True, help='Uniqmapped.bam files generated by MultiomeATAC_mito.sh, REQUIRED')
@click.option('--ncores', '-c', default=1, type=int, help='Number of cores to run the main job in parallel. default is 48')
@click.option('--files-per-core', '-f', default=1, type=int, help='Number of files each core deals with sequentially, default is 1. If memory is limited, set this number larger')
@click.option('--barcodes', '-b', default=".", help='The csv file indicating the qualified cell names. barcodes.tsv generated by RNAbc2ATAC.R, required')
@click.option('--output', '-o', default="Out_mitoConsensus", help='The name of folder to be created that will contain the analyzed results, default=Out_mitoConsensus')
@click.option('--mito-genome', '-g', default="rCRS", help='Mitochondrial genome configuration. Choose hg19, hg38, mm10, (etc.) or a custom .fasta file, Default = rCRS')
@click.option('--barcode-tag', '-bt', default="BC", help='Tag name in bam file, 10X is BC. Default = BC')
@click.option('--script-dir', '-sd', default="/lab/solexa_weissman/cweng/Packages/REDEEM-V/mitoConsensus/", help='The path to REDEEM-V/mitoConsensus/')
@click.option('--prefix', default='', help='Prefix to add to output filenames (e.g. sample name)')
def preprocess(input, ncores, files_per_core, barcodes, output, mito_genome, barcode_tag, script_dir, prefix):
    """
    This script split the mtDNA bam files for in-paralell variant calling
    
    Syntax: python Preprocess.py -i -c -f -b -o -g -bt -sd

    Acknowledgment: Inherited some of the codes from https://github.com/caleblareau/mgatk by Caleb Lareau et al. 
    """
    print(f"Starting to prep split bam files")
    print(f"Using BAM file: {input}")
    print(f"Using BAI file: {input}.bai")
    print(f"Using barcode file: {barcodes}")
    
    of = output; tf = of + "/temp"; bcbd = tf + "/barcoded_bams" # bcbd = barcoded bam directory
    folders = [of, tf, bcbd, of + "/final"] #,tf+"/sparse_matrices"
    mkfolderout = [make_folder(x) for x in folders]

    # Handle fasta requirements
    rawsg = os.popen('ls ' + script_dir + "/bin/anno/fasta/*.fasta").read().strip().split("\n")
    supported_genomes = [x.replace(script_dir + "/bin/anno/fasta/", "").replace(".fasta", "") for x in rawsg]
    fastaf, mito_chr, mito_length = handle_fasta_inference(mito_genome, supported_genomes, script_dir, "tenx", of)
    idxs = pysam.idxstats(input).split("\n")
    print(f"DEBUG: First 3 idxstats entries: {idxs[:3]}")

    # Split Cell barcode files based on the cores to use
  
    file_number = int(files_per_core)
    n_samples_observed = file_len(barcodes)
    n_per_file = math.ceil(n_samples_observed / file_number)
    print(f"DEBUG: Number of splits: {file_number}")
    print(f"DEBUG: barcodes_per_splits: {n_per_file}")
    print(f"DEBUG: Estimated barcode file length: {file_len(barcodes)}")
    print(f"DEBUG: Chunk size for splitting: {math.ceil(file_len(barcodes)/file_number)}")
    barcode_files = split_barcodes_file_new(barcodes, n_per_file, output)
    print(f"DEBUG: Generated barcode files: {barcode_files}")

    # Add this line after the debug statement for script_dir
    chunk_bam_py = script_dir + "/bin/python/chunk_barcoded_bam.py"
    print(f"DEBUG: File exists: {os.path.exists(chunk_bam_py)}")
      # Process each barcode file sequentially
    print(f"Processing {len(barcode_files)} barcode files sequentially...")
    # for i, barcode_file in enumerate(barcode_files):
    #     print(f"Processing file {i+1}/{len(barcode_files)}: {barcode_file}")
    #     split_chunk_file(barcode_file, script_dir, input, bcbd, barcode_tag, mito_chr, prefix)
    # Instead of this:

# Use this:
    process_bam_single_pass(input, barcode_files, bcbd, barcode_tag, mito_chr, prefix)
    print(f"Finished processing {len(barcode_files)} bam files")


 


if __name__ == '__main__':
    preprocess()  # Click automatically parses CLI args when the script is run

