""" 
Preprocess.py
This script split the mtDNA bam files for in-paralell variant calling

Syntax: python Preprocess.py -i -c -b -o -g -bt -sd
Options: --input or -i: uniqmapped.bam files generated by MultiomeATAC_mito.sh, REQUIRED.
         --ncores or -c: Number of cores to run the main job in parallel. REQUIRED.
         --barcodes or -b: The csv file indicating the qualified cell names. barcodes.tsv generated by RNAbc2ATAC.R, required
         --output or -o: The name of folder to be created that will contain the analyzed results, default=Out_mitoConsensus
         --mito-genome or -g: mitochondrial genome configuration. Choose hg19, hg38, mm10, (etc.) or a custom .fasta file,  Default = rCRS
         --barcode-tag or -bt: tag name in bam file, 10X is BC. Default = BC
         --script-dir or -sd: default = "/lab/solexa_weissman/cweng/Packages/REDEEM-V/mitoConsensus/ The path to REDEEM-V/mitoConsensus/

Acknowledgment: Inherited some of the codes from https://github.com/caleblareau/mgatk by Caleb Lareau et al. 
"""

import argparse
from multiprocessing import Pool
from mgatkHelp import *
from itertools import repeat
import pysam
import os
import sys
import subprocess
import time


# NEW: Added this entire function
def verify_bam_index(bam_file):
    """
    Verify that the BAM file has an index and create one if it doesn't exist.
    
    Parameters:
    bam_file (str): Path to the BAM file
    
    Returns:
    bool: True if index exists or was created successfully, False otherwise
    """
    bai_file = bam_file + ".bai"
    
    # Check if index exists
    if os.path.exists(bai_file):
        print(f"BAM index found: {bai_file}")
        # Verify index is not corrupted
        try:
            with pysam.AlignmentFile(bam_file, "rb") as bam:
                # Try accessing the index (this will fail if the index is corrupted)
                try:
                    # Just check if we can access a chromosome (any will do)
                    chrom_names = bam.references
                    if len(chrom_names) > 0:
                        bam.fetch(chrom_names[0], 1, 2)
                    return True
                except ValueError as e:
                    print(f"BAM index exists but appears to be invalid: {e}")
                    print("Will attempt to recreate the index...")
        except Exception as e:
            print(f"Error checking BAM file: {e}")
            return False
    
    # Create index if it doesn't exist or is corrupted
    print(f"Creating BAM index for {bam_file}...")
    try:
        # Try using samtools (usually faster than pysam)
        print("Attempting to index with samtools...")
        result = subprocess.run(['samtools', 'index', bam_file], 
                               stdout=subprocess.PIPE, 
                               stderr=subprocess.PIPE,
                               text=True)
        
        if result.returncode != 0:
            print(f"samtools index failed: {result.stderr}")
            print("Falling back to pysam indexing...")
            pysam.index(bam_file)
            
        # Verify the index was created
        if os.path.exists(bai_file):
            print(f"Successfully created BAM index: {bai_file}")
            return True
        else:
            print(f"Failed to create BAM index for {bam_file}")
            return False
            
    except Exception as e:
        print(f"Error creating BAM index: {e}")
        return False

def preprocess(args):
    """
    This script split the mtDNA bam files for in-paralell variant calling
    
    Syntax: python Preprocess.py -i -c -f -b -o -g -bt -sd

    Acknowledgment: Inherited some of the codes from https://github.com/caleblareau/mgatk by Caleb Lareau et al. 
    """

     # NEW: Added these verification steps
    print(f"Verifying BAM file: {args.input}")
    if not os.path.exists(args.input):
        print(f"Error: BAM file {args.input} not found.")
        sys.exit(1)
        
    if not verify_bam_index(args.input):
        print("WARNING: Unable to create or verify BAM index. Process may fail when trying to use fetch().")
        # Provide a 5 second pause to let the user see the warning
        time.sleep(5)
    
    # Extract base filename without path and extension
    input_basename = os.path.basename(args.input)
    input_name = os.path.splitext(input_basename)[0]
    
    # Create output folders with input name incorporated
    of = f"{args.output}/{input_name}"
    tf = f"{of}/temp"
    bcbd = f"{tf}/barcoded_bams" # bcdb = barcoded bam directory
    
    folders = [of, tf, bcbd, f"{of}/final"] #,tf+"/sparse_matrices"
    mkfolderout = [make_folder(x) for x in folders]

    # Handle fasta requirements
    rawsg = os.popen('ls ' + args.script_dir + "/bin/anno/fasta/*.fasta").read().strip().split("\n")
    supported_genomes = [x.replace(args.script_dir + "/bin/anno/fasta/", "").replace(".fasta", "") for x in rawsg]
    fastaf, mito_chr, mito_length = handle_fasta_inference(args.mito_genome, supported_genomes, args.script_dir, "tenx", of)
    # CHANGED: Added error handling for idxstats
    try:
        idxs = pysam.idxstats(args.input).split("\n")
    except Exception as e:
        print(f"Error accessing idxstats: {e}")
        print("This may indicate an issue with the BAM file or its index.")
        print("Will attempt to continue with the process...")
    # NEW: Added chromosome validation
    print(f"Looking for mitochondrial chromosome: {mito_chr}")
    try:
        with pysam.AlignmentFile(args.input, "rb") as bam:
            references = bam.references
            if mito_chr not in references:
                print(f"WARNING: Mitochondrial chromosome {mito_chr} not found in BAM file.")
                print(f"Available chromosomes: {', '.join(references[:10])}...")
            else:
                print(f"Found mitochondrial chromosome {mito_chr} in BAM file.")
    except Exception as e:
        print(f"Error checking BAM references: {e}")

    
    # Split Cell barcode files based on the cores to use
    file_number = int(args.ncores) * int(args.files_per_core)
    barcode_files = split_barcodes_file(args.barcodes, math.ceil(file_len(args.barcodes) / file_number), of)

       # NEW: Added more informative message

    print(f"Starting to split BAM file into {file_number} chunks using {args.ncores} cores...")

    # # Split BAM files in a parallel manner
    # pool = Pool(processes=int(args.ncores))
    # pmblah = pool.starmap(debug_split_chunk_file, zip(barcode_files, repeat(args.script_dir), repeat(args.input), repeat(bcbd), repeat(args.barcode_tag), repeat(mito_chr)))
    # pool.close()
    # Sequential processing instead of parallel
    print(f"Processing {len(barcode_files)} barcode files sequentially...")
    results = []
    for barcode_file in barcode_files:
        print(f"Processing barcode file: {barcode_file}")
        result = debug_split_chunk_file(barcode_file, args.script_dir, args.input, bcbd, args.barcode_tag, mito_chr)
        results.append(result)
        


    print(f"Split {input_basename} into {str(file_number)} bam files in {of}")

# Define the debug function
def debug_split_chunk_file(barcode_file, script_dir, bam_input, bcbd, barcode_tag, mito_chr):
    print(f"[DEBUG] Processing barcode file: {barcode_file}")
    print(f"[DEBUG] Using BAM file: {bam_input}")
    print(f"[DEBUG] Barcode tag: {barcode_tag}, Mitochondrial chromosome: {mito_chr}")
    
    # CHANGED: Added try-except block for better error handling
    try:
        result = split_chunk_file(barcode_file, script_dir, bam_input, bcbd, barcode_tag, mito_chr)
        print(f"[DEBUG] Finished processing {barcode_file}")
        return result
    except Exception as e:
        print(f"[ERROR] Failed processing {barcode_file}: {str(e)}")
        # Print the stack trace for debugging
        import traceback
        traceback.print_exc()
        return None




if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='This script splits mtDNA bam files for in-parallel variant calling',
        epilog='Acknowledgment: Inherited some of the codes from https://github.com/caleblareau/mgatk by Caleb Lareau et al.'
    )
    
    parser.add_argument('--input', '-i', 
                      required=True, 
                      help='Uniqmapped.bam files generated by MultiomeATAC_mito.sh, REQUIRED')
    
    parser.add_argument('--ncores', '-c', 
                      type=int,
                      default=48, 
                      help='Number of cores to run the main job in parallel. default is 48')
    
    parser.add_argument('--files-per-core', '-f', 
                      type=int,
                      default=1, 
                      help='Number of files each core deals with sequentially, default is 1. If memory is limited, set this number larger')
    
    parser.add_argument('--barcodes', '-b', 
                      default=".", 
                      help='The csv file indicating the qualified cell names. barcodes.tsv generated by RNAbc2ATAC.R, required')
    
    parser.add_argument('--output', '-o', 
                      default="Out_mitoConsensus", 
                      help='The name of folder to be created that will contain the analyzed results, default=Out_mitoConsensus')
    
    parser.add_argument('--mito-genome', '-g', 
                      default="rCRS", 
                      help='Mitochondrial genome configuration. Choose hg19, hg38, mm10, (etc.) or a custom .fasta file, Default = rCRS')
    
    parser.add_argument('--barcode-tag', '-bt', 
                      default="BC", 
                      help='Tag name in bam file, 10X is BC. Default = BC')
    
    parser.add_argument('--script-dir', '-sd', 
                      default="/lab/solexa_weissman/cweng/Packages/REDEEM-V/mitoConsensus/", 
                      help='The path to REDEEM-V/mitoConsensus/')
    
    args = parser.parse_args()
    preprocess(args)